#!/usr/bin/env bash

set -eo pipefail

# From a file path like /the/path/1966-09-03-name.ext
# return just the date i.e. 1966-09-03
getdate() {

		local file
		file="${1##*/}"
		echo "${file:0:10}"
}


main() {

	local file="$1"
	sed -i -E "0,/^---$/adate: $(getdate "$file")" "$file"

}

main "$@"
