#!/usr/bin/env bash

# Fix up old blog post Markdown frontmatter:
# - remove any layout: post entries
# - add a date based on the filename

set -eo pipefail

# From a file path like /the/path/1966-09-03-name.ext
# return just the date i.e. 1966-09-03
getdate() {

  local file
  file="${1##*/}"
  echo "${file:0:10}"
}

removepostlayout() {
  local file="$1"
  sed -i -E "/^layout: post$/d" "$file"
}

adddate() {

  local file="$1"
  sed -i -E "0,/^---$/adate: $(getdate "$file")" "$file"

}

main() {
  for file in "$@"; do
    removepostlayout "$file"
    adddate "$file"
  done
}

main "$@"
